### ISSUE TITLE
Only create local models to reduce memory footprint

### ISSUE THREAD

**Issue by michel2323** [exanauts/ProxAL.jl#21]
As is ProxAL creates all the models on every process. This leads to a memory bottleneck beyond a certain case size (e.g. 9241 PEGASE).

**Comment by AnirudhSubramanyam** [comment]
It appears that each process creates its local models with `blocknlp_recreate`..?
https://github.com/exanauts/ProxAL.jl/blob/c76f5d12ad62c251ca487049a6dcbd30c59a85c3/src/Evaluators/ProxALEvalutor.jl#L129-L134

**Comment by michel2323** [comment]
I looked a bit into this problem and it seems ProxAL is not the issue here as @AnirudhSubramanyam correctly mentions. I tried JuMP and it clearly shows high memory usage for the first run when compiling. Using the ExaPF backend this is much better. @kibaekkim can you show an instance where you still have a concern? I think this should be fine with ExaTron and ExaPF.

**Comment by michel2323** [comment]
Mostly fixed by https://github.com/exanauts/ProxAL.jl/pull/26 .
