### ISSUE TITLE
ExaTron Interface

### ISSUE THREAD

**Issue by michel2323** [exanauts/ProxAL.jl#22]
Interace to ExaTron using similar API to `AbstractBlockModel`.

**Comment by kibaekkim** [comment]
Added myself and @youngdae as assignees too.
@youngdae implements at the ExaTron side, and @frapac does at the ProxAL side.

**Comment by michel2323** [comment]
Done by @frapac and merged https://github.com/exanauts/ProxAL.jl/pull/24 .
